# Generated by Django 4.2.2 on 2023-06-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_collected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uid', models.CharField(default='Id not given', max_length=400)),
                ('userid', models.CharField(blank=True, default='something', max_length=400, null=True)),
                ('ip', models.CharField(blank=True, default='something', max_length=40, null=True)),
                ('date', models.DateField()),
                ('time_zone', models.CharField(blank=True, default='UTC', max_length=40, null=True)),
                ('language', models.CharField(blank=True, default='en-US', max_length=40, null=True)),
                ('system_fonts', models.CharField(blank=True, default='Arial', max_length=10000, null=True)),
                ('time_collected', models.TimeField(default=0)),
                ('city', models.CharField(blank=True, default='SOME STRING', max_length=20, null=True)),
                ('region', models.CharField(blank=True, default='SOME STRING', max_length=20, null=True)),
                ('country', models.CharField(blank=True, default='SOME STRING', max_length=40, null=True)),
                ('browser_name', models.CharField(default='Something', max_length=400)),
                ('browser_version', models.CharField(default='Something', max_length=400)),
                ('os_family', models.CharField(default='something', max_length=400)),
                ('os_version', models.CharField(default='Something', max_length=400)),
                ('screensize', models.CharField(default=0, max_length=20)),
                ('screen_res_height', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('screen_res_width', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('plugins', models.CharField(blank=True, default='Something', max_length=200, null=True)),
                ('canvas', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('webgl', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('ua_totaltime', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('ip_totaltime', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('timezone_totaltime', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('location_totaltime', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('screensize_totaltime', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('system_fonts_totaltime', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('browser_fonts_totaltime', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('plugins_totaltime', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('canvas_totaltime', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('webgl_totaltime', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('lang_totaltime', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, default=0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0, null=True)),
                ('geolocation_totaltime', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('overall_totaltime', models.CharField(blank=True, default=0, max_length=200, null=True)),
            ],
        ),
    ]
