# Generated by Django 4.2.2 on 2023-07-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_collected',
            name='latlong',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
