# Generated by Django 4.2.2 on 2023-07-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_data_collected_latlong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_collected',
            name='latlong',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
