# Generated by Django 4.2.2 on 2023-07-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_data_collected_latlong'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_collected',
            name='location',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
