# Generated by Django 4.2.2 on 2023-07-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_data_collected_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_collected',
            name='browser_fonts_totaltime',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='canvas_totaltime',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='ip_totaltime',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='lang_totaltime',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='location_totaltime',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='plugins_totaltime',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='screensize_totaltime',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='system_fonts_totaltime',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='timezone_totaltime',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='ua_totaltime',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='webgl_totaltime',
        ),
    ]
