# Generated by Django 4.2.2 on 2023-07-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_data_collected_browser_fonts_totaltime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_collected',
            name='browser',
            field=models.TextField(blank=True, default='0', null=True),
        ),
    ]
