# Generated by Django 4.2.2 on 2023-07-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_data_collected_browser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_collected',
            name='browser',
            field=models.TextField(blank=True, default='0', null=True),
        ),
    ]
