# Generated by Django 4.2.2 on 2023-07-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_data_collected_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_collected',
            name='system_fonts',
        ),
    ]
