# Generated by Django 4.2.2 on 2023-07-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_data_collected_system_fonts'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_collected',
            name='system',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
