# Generated by Django 4.2.2 on 2023-07-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_system_data_collected_system_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_collected',
            old_name='overall_totaltime',
            new_name='rtt',
        ),
        migrations.RenameField(
            model_name='data_collected',
            old_name='time_collected',
            new_name='system_time',
        ),
    ]
