# Generated by Django 4.2.2 on 2023-07-03 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_overall_totaltime_data_collected_rtt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_collected',
            old_name='system_time',
            new_name='time_collected',
        ),
    ]
