# Generated by Django 4.2.2 on 2023-07-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_data_collected_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_collected',
            old_name='system_time',
            new_name='login_time',
        ),
        migrations.RenameField(
            model_name='data_collected',
            old_name='screensize',
            new_name='screen_size',
        ),
    ]
