# Generated by Django 4.2.2 on 2023-07-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_system_time_data_collected_login_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_collected',
            old_name='geolocation_totaltime',
            new_name='start_week',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='browser_name',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='browser_version',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='city',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='country',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='os_family',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='os_version',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='region',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='screen_res_height',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='screen_res_width',
        ),
    ]
