# Generated by Django 4.2.2 on 2023-07-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_geolocation_totaltime_data_collected_start_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_collected',
            name='plugins',
        ),
        migrations.AddField(
            model_name='data_collected',
            name='login_status',
            field=models.CharField(blank=True, default='E', max_length=200, null=True),
        ),
    ]
