# Generated by Django 4.2.2 on 2023-07-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_data_collected_plugins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_collected',
            name='login_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
