# Generated by Django 4.2.2 on 2023-07-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_data_collected_login_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_collected',
            old_name='date',
            new_name='prev_date',
        ),
    ]
